import type { Build } from './types'

// Sample builds for the conveyor belt showcase
// In production these would come from the aggregator indexer

export const builds: Build[] = [
  {
    id: 'quinn-personal',
    name: 'Personal Assistant',
    description: 'Full-featured personal AI with voice, smart home, calendar, and iMessage integration',
    source: 'github',
    repoUrl: 'https://github.com/bolander72/quinn-build',
    owner: 'bolander72',
    stars: 42,
    creator: '@Bolander72',
    createdAt: '2026-03-11',
    tags: ['personal', 'voice', 'smart-home', 'calendar'],
    keyCount: 6,
    content: {},
    compatibility: ['openclaw', 'claude-code'],
    permissions: ['filesystem', 'web-search', 'email', 'calendar', 'smart-home', 'message'],
    trustTier: 'verified',
    items: [
      { name: 'Claude Opus', color: 'text-purple-400' },
      { name: 'Claude Sonnet', color: 'text-blue-400' },
      { name: 'Qwen 3.5:4b', color: 'text-rc-green' },
      { name: 'Whisper (local)', color: 'text-rc-text-dim' },
      { name: 'Voice Chat', color: 'text-pink-400' },
      { name: 'Frontend Design', color: 'text-violet-400' },
      { name: 'Coding Agent', color: 'text-rc-green' },
      { name: 'Web Research', color: 'text-rc-cyan' },
      { name: 'iMessage', color: 'text-green-400' },
      { name: 'Calendar', color: 'text-rc-red' },
      { name: 'Email', color: 'text-blue-400' },
      { name: 'Smart Home', color: 'text-rc-yellow' },
      { name: 'GitHub', color: 'text-rc-text' },
      { name: 'Heartbeats', color: 'text-rose-400' },
      { name: 'Cron Jobs', color: 'text-blue-400' },
      { name: 'LCM (lossless)', color: 'text-rc-green' },
      { name: 'Daily Notes', color: 'text-amber-400' },
    ],
  },
  {
    id: 'devbot-coder',
    name: 'Full-Stack Dev',
    description: 'Specialized coding agent with PR review, CI/CD monitoring, and architecture decision tracking',
    source: 'github',
    repoUrl: 'https://github.com/synthwave-dev/devbot-coder',
    owner: 'synthwave-dev',
    stars: 156,
    creator: '@synthwave_dev',
    createdAt: '2026-03-10',
    tags: ['coding', 'devops', 'github', 'ci-cd'],
    keyCount: 5,
    content: {},
    compatibility: ['openclaw', 'claude-code', 'cursor', 'windsurf'],
    permissions: ['filesystem', 'exec', 'web-search'],
    trustTier: 'community',
    items: [
      { name: 'Claude Sonnet', color: 'text-blue-400' },
      { name: 'Codex', color: 'text-rc-green' },
      { name: 'GPT-5.2', color: 'text-emerald-400' },
      { name: 'Coding Agent', color: 'text-rc-green' },
      { name: 'PR Review', color: 'text-orange-400' },
      { name: 'CI/CD Monitor', color: 'text-blue-400' },
      { name: 'DB Migrations', color: 'text-rc-yellow' },
      { name: 'GitHub', color: 'text-rc-text' },
      { name: 'Linear', color: 'text-violet-400' },
      { name: 'Slack', color: 'text-purple-400' },
      { name: 'Vercel', color: 'text-rc-text' },
      { name: 'CI Watcher', color: 'text-rc-red' },
      { name: 'Nightly Tests', color: 'text-blue-400' },
      { name: 'Codebase Map', color: 'text-rc-cyan' },
      { name: 'Architecture Decisions', color: 'text-amber-400' },
    ],
  },
  {
    id: 'homeguard-smart',
    name: 'Smart Home Manager',
    description: 'Local-first smart home automation with security alerts, energy monitoring, and voice control',
    source: 'clawhub',
    creator: '@homelab_nick',
    createdAt: '2026-03-08',
    tags: ['smart-home', 'security', 'automation', 'local'],
    keyCount: 4,
    content: {},
    compatibility: ['openclaw'],
    permissions: ['smart-home', 'message'],
    trustTier: 'community',
    items: [
      { name: 'Qwen 3.5:4b', color: 'text-rc-green' },
      { name: 'Whisper (local)', color: 'text-rc-text-dim' },
      { name: 'Security Alerts', color: 'text-rc-red' },
      { name: 'Energy Monitor', color: 'text-rc-green' },
      { name: 'Climate Control', color: 'text-rc-yellow' },
      { name: 'Voice Control', color: 'text-pink-400' },
      { name: 'Home Assistant', color: 'text-blue-400' },
      { name: 'HomeKit', color: 'text-rc-text' },
      { name: 'Telegram', color: 'text-sky-400' },
      { name: 'UniFi Protect', color: 'text-violet-400' },
      { name: 'Routines', color: 'text-rc-cyan' },
      { name: 'Motion Alerts', color: 'text-rose-400' },
      { name: 'Night Mode', color: 'text-purple-400' },
      { name: 'Device Registry', color: 'text-rc-green' },
    ],
  },
  {
    id: 'research-deep',
    name: 'Research Analyst',
    description: 'Deep research agent with PDF analysis, citation management, and knowledge graph building',
    source: 'github',
    repoUrl: 'https://github.com/deep-research/iris',
    owner: 'deep-research',
    stars: 89,
    creator: '@deep_research',
    createdAt: '2026-03-06',
    tags: ['research', 'analysis', 'citations', 'knowledge'],
    keyCount: 6,
    content: {},
    compatibility: ['openclaw', 'claude-code'],
    permissions: ['filesystem', 'web-search', 'browser'],
    trustTier: 'verified',
    items: [
      { name: 'Claude Opus', color: 'text-purple-400' },
      { name: 'Perplexity', color: 'text-sky-400' },
      { name: 'GPT-5.2', color: 'text-emerald-400' },
      { name: 'Deep Research', color: 'text-rc-cyan' },
      { name: 'PDF Analysis', color: 'text-rc-red' },
      { name: 'Web Scraping', color: 'text-rc-green' },
      { name: 'Citation Manager', color: 'text-amber-400' },
      { name: 'Notion', color: 'text-rc-text' },
      { name: 'Zotero', color: 'text-rc-red' },
      { name: 'Google Scholar', color: 'text-blue-400' },
      { name: 'ArXiv Watch', color: 'text-orange-400' },
      { name: 'Weekly Digest', color: 'text-blue-400' },
      { name: 'Source Index', color: 'text-rc-green' },
      { name: 'Knowledge Graph', color: 'text-rc-yellow' },
    ],
  },
  {
    id: 'marketing-pro',
    name: 'Growth Marketer',
    description: 'Complete marketing automation with copywriting, SEO audits, A/B testing, and campaign tracking',
    source: 'github',
    repoUrl: 'https://github.com/growthcraft/spark',
    owner: 'growthcraft',
    stars: 234,
    creator: '@growthcraft',
    createdAt: '2026-03-05',
    tags: ['marketing', 'seo', 'copywriting', 'analytics'],
    keyCount: 5,
    content: {},
    compatibility: ['openclaw', 'claude-code', 'cursor'],
    permissions: ['web-search', 'browser'],
    trustTier: 'verified',
    items: [
      { name: 'Claude Sonnet', color: 'text-blue-400' },
      { name: 'GPT-5.2', color: 'text-emerald-400' },
      { name: 'Copywriting', color: 'text-pink-400' },
      { name: 'SEO Audit', color: 'text-rc-green' },
      { name: 'A/B Testing', color: 'text-rc-yellow' },
      { name: 'Social Content', color: 'text-violet-400' },
      { name: 'Google Analytics', color: 'text-rc-yellow' },
      { name: 'Stripe', color: 'text-purple-400' },
      { name: 'Mailchimp', color: 'text-rc-yellow' },
      { name: 'Campaign Reports', color: 'text-rc-cyan' },
      { name: 'Competitor Watch', color: 'text-rc-red' },
      { name: 'Campaign History', color: 'text-amber-400' },
    ],
  },
  {
    id: 'finance-tracker',
    name: 'Finance Manager',
    description: 'Personal finance automation with expense tracking, receipt OCR, budget alerts, and tax prep',
    source: 'clawhub',
    creator: '@money_moves',
    createdAt: '2026-02-28',
    tags: ['finance', 'budgeting', 'taxes', 'automation'],
    keyCount: 4,
    content: {},
    compatibility: ['openclaw'],
    permissions: ['filesystem'],
    trustTier: 'unreviewed',
    items: [
      { name: 'Claude Sonnet', color: 'text-blue-400' },
      { name: 'Qwen 3.5:4b', color: 'text-rc-green' },
      { name: 'Expense Tracking', color: 'text-rc-red' },
      { name: 'Receipt OCR', color: 'text-rc-yellow' },
      { name: 'Budget Alerts', color: 'text-orange-400' },
      { name: 'Tax Prep', color: 'text-rc-cyan' },
      { name: 'Stripe', color: 'text-purple-400' },
      { name: 'Plaid', color: 'text-rc-green' },
      { name: 'Google Sheets', color: 'text-rc-green' },
      { name: 'Daily Summary', color: 'text-rc-cyan' },
      { name: 'Bill Reminders', color: 'text-rc-yellow' },
      { name: 'Transaction Log', color: 'text-rc-green' },
    ],
  },
  {
    id: 'pm-coordinator',
    name: 'Project Manager',
    description: 'Team coordination with standup reports, sprint planning, blocker detection, and deadline alerts',
    source: 'github',
    repoUrl: 'https://github.com/pm-sarah/relay',
    owner: 'pm-sarah',
    stars: 67,
    creator: '@pm_sarah',
    createdAt: '2026-03-09',
    tags: ['project-management', 'team', 'agile', 'coordination'],
    keyCount: 5,
    content: {},
    compatibility: ['openclaw', 'claude-code'],
    permissions: ['calendar', 'message'],
    trustTier: 'community',
    items: [
      { name: 'Claude Opus', color: 'text-purple-400' },
      { name: 'Claude Sonnet', color: 'text-blue-400' },
      { name: 'Standup Reports', color: 'text-rc-green' },
      { name: 'Sprint Planning', color: 'text-rc-cyan' },
      { name: 'Blocker Detection', color: 'text-rc-red' },
      { name: 'Linear', color: 'text-violet-400' },
      { name: 'Slack', color: 'text-purple-400' },
      { name: 'Google Calendar', color: 'text-blue-400' },
      { name: 'Notion', color: 'text-rc-text' },
      { name: 'Morning Standup', color: 'text-rc-green' },
      { name: 'Deadline Alerts', color: 'text-rc-red' },
      { name: 'Team Roster', color: 'text-rc-cyan' },
      { name: 'Project Roadmap', color: 'text-rc-green' },
    ],
  },
  {
    id: 'content-creator',
    name: 'Content Studio',
    description: 'Multi-platform content creation with blog writing, social scheduling, newsletters, and video scripts',
    source: 'github',
    repoUrl: 'https://github.com/creative-ops/muse',
    owner: 'creative-ops',
    stars: 178,
    creator: '@creative_ops',
    createdAt: '2026-03-07',
    tags: ['content', 'social-media', 'writing', 'creativity'],
    keyCount: 5,
    content: {},
    compatibility: ['openclaw', 'claude-code', 'cursor'],
    permissions: ['web-search', 'browser'],
    trustTier: 'verified',
    items: [
      { name: 'Claude Opus', color: 'text-purple-400' },
      { name: 'GPT-5.2', color: 'text-emerald-400' },
      { name: 'Blog Writing', color: 'text-rc-cyan' },
      { name: 'Social Content', color: 'text-violet-400' },
      { name: 'Newsletter', color: 'text-rc-yellow' },
      { name: 'Video Scripts', color: 'text-pink-400' },
      { name: 'WordPress', color: 'text-blue-400' },
      { name: 'Buffer', color: 'text-rc-text' },
      { name: 'Figma', color: 'text-purple-400' },
      { name: 'YouTube', color: 'text-rc-red' },
      { name: 'Content Calendar', color: 'text-rc-yellow' },
      { name: 'Publish Queue', color: 'text-rc-green' },
      { name: 'Content Archive', color: 'text-amber-400' },
    ],
  },
]
