import type { Build } from './types'

// Sample builds for the aggregator showcase
// In production these would come from the indexer (GitHub, ClawHub, skills.sh, etc.)

export const builds: Build[] = [
  {
    id: 'garrytan-gstack',
    name: 'gstack',
    description: 'Garry Tan\'s Claude Code stack: systematic planning, code review, browser automation, and retro. Battle-tested by YC founders.',
    source: 'github',
    repoUrl: 'https://github.com/garrytan/gstack',
    owner: 'garrytan',
    stars: 2547,
    forks: 189,
    lastUpdated: '2026-03-12',
    creator: '@garrytan',
    createdAt: '2026-01-15',
    tags: ['planning', 'review', 'shipping', 'automation', 'startup'],
    compatibility: ['claude-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'CLAUDE.md'],
    skills: [
      { name: 'plan-ceo-review', description: 'CEO-level planning and prioritization before building features' },
      { name: 'plan-eng-review', description: 'Engineering review of implementation approach and edge cases' },
      { name: 'review', description: 'Code review with startup velocity focus — practical feedback, not nitpicks' },
      { name: 'ship', description: 'Deploy and announce features with confidence' },
      { name: 'browse', description: 'Browser automation for testing user flows and competitor research' },
      { name: 'qa', description: 'Systematic QA checklist for critical paths' },
      { name: 'setup-browser-cookies', description: 'Authenticate browser sessions for realistic testing' },
      { name: 'retro', description: 'Post-ship retrospective: what worked, what didn\'t, what\'s next' },
    ],
  },
  {
    id: 'anthropics-skills',
    name: 'Anthropic Skills',
    description: 'Official skill collection from Anthropic: PDF, Word, PowerPoint, Excel extraction, image analysis, and data processing. Universal compatibility.',
    source: 'github',
    repoUrl: 'https://github.com/anthropics/skills',
    owner: 'anthropics',
    stars: 3241,
    forks: 412,
    lastUpdated: '2026-03-13',
    creator: '@anthropic',
    createdAt: '2026-01-08',
    tags: ['documents', 'data', 'official', 'extraction', 'analysis'],
    compatibility: ['claude-code', 'claude', 'openai-codex', 'github-copilot', 'vs-code', 'cursor', 'gemini-cli', 'roo-code', 'goose', 'openhands', 'opencode', 'amp', 'junie', 'mux', 'letta', 'firebender', 'trae', 'factory', 'pi', 'databricks', 'piebald', 'agentman', 'spring-ai', 'autohand', 'mistral-vibe', 'command-code', 'ona', 'vt-code', 'qodo', 'laravel-boost', 'emdash', 'snowflake', 'openclaw'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'pdf', description: 'Extract text, tables, and metadata from PDF documents' },
      { name: 'docx', description: 'Parse Word documents with formatting preservation' },
      { name: 'pptx', description: 'Extract slide content and speaker notes from PowerPoint' },
      { name: 'xlsx', description: 'Process Excel spreadsheets with formula and chart support' },
      { name: 'image-analysis', description: 'Analyze images for text, objects, and visual context' },
      { name: 'markdown-converter', description: 'Convert between document formats via markdown' },
      { name: 'csv-processor', description: 'Clean and transform CSV data with schema detection' },
      { name: 'json-validator', description: 'Validate and format JSON with schema enforcement' },
    ],
  },
  {
    id: 'microsoft-github-copilot-azure',
    name: 'GitHub Copilot for Azure',
    description: 'Microsoft\'s official Azure Copilot skills: infrastructure provisioning, monitoring, cost optimization, and security scanning.',
    source: 'skillssh',
    repoUrl: 'https://github.com/microsoft/github-copilot-for-azure',
    owner: 'microsoft',
    stars: 1876,
    forks: 234,
    lastUpdated: '2026-03-11',
    creator: '@microsoft',
    createdAt: '2026-02-01',
    tags: ['azure', 'cloud', 'devops', 'infrastructure', 'official'],
    compatibility: ['github-copilot', 'vs-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'azure-provision', description: 'Create and configure Azure resources with best practices' },
      { name: 'azure-monitor', description: 'Set up monitoring, alerts, and dashboards' },
      { name: 'azure-cost', description: 'Analyze and optimize cloud spending' },
      { name: 'azure-security', description: 'Security scanning and compliance checks' },
      { name: 'azure-deploy', description: 'Deploy applications to App Service, Functions, and AKS' },
    ],
  },
  {
    id: 'quinn-personal-assistant',
    name: 'Personal Assistant (OpenClaw)',
    description: 'Full-featured personal AI: voice chat, smart home control, calendar management, iMessage integration. Privacy-first, runs locally.',
    source: 'github',
    repoUrl: 'https://github.com/bolander72/quinn-build',
    owner: 'bolander72',
    stars: 142,
    forks: 18,
    lastUpdated: '2026-03-13',
    creator: '@bolander72',
    createdAt: '2026-02-20',
    tags: ['personal', 'voice', 'smart-home', 'calendar', 'local-first'],
    compatibility: ['openclaw'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md', 'SOUL.md', 'AGENTS.md', 'openclaw.json'],
    skills: [
      { name: 'voice-loop', description: 'Local voice chat with Whisper (STT) and Kokoro (TTS)' },
      { name: 'imessage-voice-reply', description: 'Send voice messages in iMessage as native bubbles' },
      { name: 'apple-notes', description: 'Create, search, and manage Apple Notes via memo CLI' },
      { name: 'apple-reminders', description: 'Add and complete reminders with natural language' },
      { name: 'caldir', description: 'Read/write calendar events across iCloud and Google' },
      { name: 'smart-home', description: 'Control lights, thermostat, garage, cameras via Home Assistant' },
      { name: 'bluebubbles', description: 'Send and receive iMessages' },
      { name: 'himalaya', description: 'Email management via IMAP/SMTP' },
      { name: 'weather', description: 'Current weather and forecasts' },
      { name: 'github', description: 'Issues, PRs, CI monitoring via gh CLI' },
      { name: 'heartbeat', description: 'Proactive daily check-ins and status updates' },
    ],
  },
  {
    id: 'cursor-rules-collection',
    name: 'Cursor Rules Collection',
    description: 'Curated .cursorrules for popular frameworks: React, Next.js, Vue, Svelte, FastAPI, Django. Opinionated coding standards and best practices.',
    source: 'github',
    repoUrl: 'https://github.com/PatrickJS/awesome-cursorrules',
    owner: 'PatrickJS',
    stars: 4123,
    forks: 567,
    lastUpdated: '2026-03-10',
    creator: '@PatrickJS',
    createdAt: '2025-11-12',
    tags: ['coding', 'frameworks', 'standards', 'cursor', 'rules'],
    compatibility: ['cursor', 'windsurf'],
    trustTier: 'community',
    detectedFiles: ['.cursorrules', 'SKILL.md'],
    skills: [
      { name: 'react-rules', description: 'React best practices: hooks, composition, performance' },
      { name: 'nextjs-rules', description: 'Next.js patterns: App Router, server components, caching' },
      { name: 'vue-rules', description: 'Vue 3 conventions: Composition API, Pinia, TypeScript' },
      { name: 'svelte-rules', description: 'Svelte coding style and SvelteKit patterns' },
      { name: 'fastapi-rules', description: 'FastAPI structure: dependency injection, async patterns' },
      { name: 'django-rules', description: 'Django conventions: class-based views, ORM best practices' },
      { name: 'typescript-rules', description: 'TypeScript strict mode and type safety patterns' },
    ],
  },
  {
    id: 'devops-automation',
    name: 'DevOps Automation Suite',
    description: 'End-to-end DevOps workflows: CI/CD pipelines, infrastructure as code, monitoring, incident response. Multi-cloud support.',
    source: 'github',
    repoUrl: 'https://github.com/devops-toolkit/agent-skills',
    owner: 'devops-toolkit',
    stars: 891,
    forks: 127,
    lastUpdated: '2026-03-09',
    creator: '@devops_toolkit',
    createdAt: '2026-01-22',
    tags: ['devops', 'ci-cd', 'infrastructure', 'monitoring', 'automation'],
    compatibility: ['claude-code', 'github-copilot', 'cursor', 'openclaw'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'github-actions', description: 'Create and debug GitHub Actions workflows' },
      { name: 'terraform', description: 'Write and validate Terraform configurations' },
      { name: 'kubernetes', description: 'Deploy and troubleshoot Kubernetes manifests' },
      { name: 'docker', description: 'Build optimized Dockerfiles and compose configs' },
      { name: 'monitoring-setup', description: 'Configure Prometheus, Grafana, and alerting' },
      { name: 'incident-response', description: 'Runbooks and playbooks for common incidents' },
      { name: 'log-analysis', description: 'Parse and analyze logs to find root causes' },
    ],
  },
  {
    id: 'marketing-automation',
    name: 'Marketing Automation Stack',
    description: 'SEO optimization, content generation, email campaigns, analytics tracking. Built for growth teams and solo founders.',
    source: 'clawhub',
    creator: '@growth_hacker',
    createdAt: '2026-02-15',
    tags: ['marketing', 'seo', 'content', 'analytics', 'automation'],
    compatibility: ['claude-code', 'claude', 'openclaw'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'seo-audit', description: 'Technical SEO analysis and recommendations' },
      { name: 'content-generator', description: 'Blog posts, landing pages, social media copy' },
      { name: 'email-sequence', description: 'Drip campaigns and nurture sequences' },
      { name: 'analytics-tracking', description: 'Set up GA4, UTM parameters, conversion tracking' },
      { name: 'competitor-research', description: 'Analyze competitor strategies and keywords' },
      { name: 'ab-test-setup', description: 'Design and implement A/B tests' },
    ],
  },
  {
    id: 'data-science-toolkit',
    name: 'Data Science Toolkit',
    description: 'Data cleaning, exploratory analysis, visualization, ML model training. Jupyter-native workflows with pandas, scikit-learn, and PyTorch.',
    source: 'github',
    repoUrl: 'https://github.com/data-sci-tools/agent-skills',
    owner: 'data-sci-tools',
    stars: 1234,
    forks: 198,
    lastUpdated: '2026-03-08',
    creator: '@data_sci_pro',
    createdAt: '2026-01-30',
    tags: ['data-science', 'ml', 'analysis', 'visualization', 'python'],
    compatibility: ['claude-code', 'github-copilot', 'cursor', 'jupyter'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'data-cleaning', description: 'Handle missing values, outliers, and type conversions' },
      { name: 'eda', description: 'Exploratory data analysis with statistical summaries' },
      { name: 'visualization', description: 'Create charts with matplotlib, seaborn, plotly' },
      { name: 'feature-engineering', description: 'Generate and select features for ML models' },
      { name: 'model-training', description: 'Train and evaluate scikit-learn and PyTorch models' },
      { name: 'notebook-export', description: 'Export Jupyter notebooks to reports and slides' },
    ],
  },
  {
    id: 'security-hardening',
    name: 'Security Hardening',
    description: 'Security-first development: dependency scanning, secret detection, code review for vulnerabilities, compliance checks.',
    source: 'github',
    repoUrl: 'https://github.com/sec-tools/agent-skills',
    owner: 'sec-tools',
    stars: 756,
    forks: 89,
    lastUpdated: '2026-03-07',
    creator: '@sec_researcher',
    createdAt: '2026-02-10',
    tags: ['security', 'compliance', 'scanning', 'hardening'],
    compatibility: ['claude-code', 'github-copilot', 'cursor'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'dependency-scan', description: 'Scan for vulnerable dependencies and suggest fixes' },
      { name: 'secret-detection', description: 'Find exposed API keys, passwords, tokens in code' },
      { name: 'code-review-security', description: 'Identify SQL injection, XSS, and other vulnerabilities' },
      { name: 'compliance-check', description: 'Verify SOC 2, GDPR, HIPAA compliance requirements' },
      { name: 'penetration-testing', description: 'Automated security testing scripts' },
    ],
  },
  {
    id: 'ecommerce-assistant',
    name: 'E-commerce Assistant',
    description: 'Shopify store management, inventory tracking, customer support automation, sales analytics. Built for online store owners.',
    source: 'clawhub',
    creator: '@ecom_builder',
    createdAt: '2026-02-28',
    tags: ['ecommerce', 'shopify', 'inventory', 'customer-support'],
    compatibility: ['openclaw', 'claude'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'shopify-orders', description: 'Manage orders, refunds, and fulfillment' },
      { name: 'inventory-sync', description: 'Track inventory across multiple channels' },
      { name: 'customer-support', description: 'Automated responses to common questions' },
      { name: 'sales-analytics', description: 'Daily sales reports and trend analysis' },
      { name: 'product-descriptions', description: 'Generate SEO-optimized product copy' },
    ],
  },
]
