import type { Kit } from './types'

// Sample kits showcasing real repos
// In production these would come from the registry + GitHub API indexing

export const kits: Kit[] = [
  {
    id: '092d35eb-eb8b-4ce2-a57b-6788657263f3',
    name: 'Anthropic Skills',
    description: 'Official skill collection from Anthropic: document processing, frontend design, web app testing, MCP builder, and more. The reference implementation for Agent Skills.',
    source: 'github',
    repoUrl: 'https://github.com/anthropics/skills',
    owner: 'anthropics',
    stars: 93475,
    forks: 10014,
    lastUpdated: '2026-03-06',
    creator: '@anthropic',
    createdAt: '2025-06-16',
    tags: ['documents', 'design', 'official', 'testing', 'mcp'],
    compatibility: ['claude-code', 'claude', 'openai-codex', 'github-copilot', 'vs-code', 'cursor', 'gemini-cli', 'roo-code', 'goose', 'openclaw'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md'],
    skillCount: 17,
  },
  {
    id: '984c0770-c52b-4d3a-b6b5-4057f22abe00',
    name: 'Awesome CursorRules',
    description: '179 curated .cursorrules for popular frameworks: React, Next.js, Vue, Svelte, FastAPI, Django, and more. The definitive collection of Cursor AI configurations.',
    source: 'github',
    repoUrl: 'https://github.com/PatrickJS/awesome-cursorrules',
    owner: 'PatrickJS',
    stars: 38455,
    forks: 3256,
    lastUpdated: '2025-10-24',
    creator: '@PatrickJS',
    createdAt: '2024-09-01',
    tags: ['cursor', 'rules', 'frameworks', 'coding', 'standards'],
    compatibility: ['cursor', 'windsurf'],
    trustTier: 'community',
    detectedFiles: ['.cursorrules'],
    skillCount: 179,
  },
  {
    id: '06465063-6a42-410f-9240-ee3ebce78bc9',
    name: 'gstack',
    description: 'Garry Tan\'s Claude Code stack: CEO review, engineering review, code review, browser QA, shipping, and retro. Battle-tested by YC founders.',
    source: 'github',
    repoUrl: 'https://github.com/garrytan/gstack',
    owner: 'garrytan',
    stars: 10243,
    forks: 1222,
    lastUpdated: '2026-03-14',
    creator: '@garrytan',
    createdAt: '2026-01-15',
    tags: ['planning', 'review', 'shipping', 'automation', 'startup'],
    compatibility: ['claude-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'CLAUDE.md'],
    skillCount: 8,
  },
  {
    id: '984d745e-07a7-45cf-979f-43563b605061',
    name: 'Awesome Copilot',
    description: 'GitHub\'s official community collection: 100+ skills, hooks, agents, and configurations for GitHub Copilot. Instructions, workflows, and plugins.',
    source: 'github',
    repoUrl: 'https://github.com/github/awesome-copilot',
    owner: 'github',
    stars: 25167,
    forks: 2881,
    lastUpdated: '2026-03-13',
    creator: '@github',
    createdAt: '2025-06-11',
    tags: ['copilot', 'github', 'official', 'agents', 'workflows'],
    compatibility: ['github-copilot', 'vs-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'AGENTS.md'],
    skillCount: 100,
  },
  {
    id: 'd376e7d0-5191-4fe9-8802-340721587088',
    name: 'Vercel Agent Skills',
    description: 'Vercel\'s official agent skills: React best practices, web design guidelines, composition patterns, and deploy-to-Vercel automation.',
    source: 'github',
    repoUrl: 'https://github.com/vercel-labs/agent-skills',
    owner: 'vercel-labs',
    stars: 22994,
    forks: 2066,
    lastUpdated: '2026-03-12',
    creator: '@vercel',
    createdAt: '2025-12-08',
    tags: ['vercel', 'react', 'design', 'deploy', 'official'],
    compatibility: ['claude-code', 'cursor', 'github-copilot', 'vs-code', 'gemini-cli'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'AGENTS.md', 'CLAUDE.md'],
    skillCount: 5,
  },
  {
    id: 'bc31b9a3-0d7e-43c6-a43e-d563fb629768',
    name: 'GitHub Copilot for Azure',
    description: 'Microsoft\'s official Azure Copilot skills: cloud deployment, cost optimization, diagnostics, compliance, AI gateway, and 20+ more.',
    source: 'github',
    repoUrl: 'https://github.com/microsoft/GitHub-Copilot-for-Azure',
    owner: 'microsoft',
    stars: 154,
    forks: 100,
    lastUpdated: '2026-03-14',
    creator: '@microsoft',
    createdAt: '2024-10-01',
    tags: ['azure', 'cloud', 'devops', 'infrastructure', 'official'],
    compatibility: ['github-copilot', 'vs-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md'],
    skillCount: 25,
  },
  {
    id: 'b5ab332f-8c0f-443c-9680-f25c17638674',
    name: 'Planning with Files',
    description: 'Manus-style persistent markdown planning for Claude Code. The workflow pattern behind the $2B acquisition — structured thinking with file-based plans.',
    source: 'github',
    repoUrl: 'https://github.com/OthmanAdi/planning-with-files',
    owner: 'OthmanAdi',
    stars: 16061,
    forks: 1476,
    lastUpdated: '2026-03-14',
    creator: '@OthmanAdi',
    createdAt: '2026-01-03',
    tags: ['planning', 'workflow', 'methodology', 'claude-code'],
    compatibility: ['claude-code'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skillCount: 1,
  },
  {
    id: 'c1330bf7-19dd-4830-a6de-9ed3d27b7aba',
    name: 'Claude Scientific Skills',
    description: '200+ skills for research, science, engineering, and finance. Covers bioinformatics, chemistry, data analysis, quantum computing, and scientific writing.',
    source: 'github',
    repoUrl: 'https://github.com/K-Dense-AI/claude-scientific-skills',
    owner: 'K-Dense-AI',
    stars: 14872,
    forks: 1635,
    lastUpdated: '2026-03-11',
    creator: '@K-Dense-AI',
    createdAt: '2025-10-19',
    tags: ['science', 'research', 'bioinformatics', 'data-analysis', 'academic'],
    compatibility: ['claude-code', 'claude'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skillCount: 200,
  },
]
