import type { Kit } from './types'

// Sample kits showcasing real repos and skills
// In production these would come from the indexer (GitHub, ClawHub, skills.sh, etc.)

export const kits: Kit[] = [
  {
    id: 'anthropics-skills',
    name: 'Anthropic Skills',
    description: 'Official skill collection from Anthropic: document processing, frontend design, web app testing, MCP builder, and more. The reference implementation for Agent Skills.',
    source: 'github',
    repoUrl: 'https://github.com/anthropics/skills',
    owner: 'anthropics',
    stars: 93475,
    forks: 10014,
    lastUpdated: '2026-03-06',
    creator: '@anthropic',
    createdAt: '2025-06-16',
    tags: ['documents', 'design', 'official', 'testing', 'mcp'],
    compatibility: ['claude-code', 'claude', 'openai-codex', 'github-copilot', 'vs-code', 'cursor', 'gemini-cli', 'roo-code', 'goose', 'openclaw'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'pdf', description: 'Extract text, tables, and metadata from PDF documents', path: 'skills/pdf' },
      { name: 'docx', description: 'Parse Word documents with formatting preservation', path: 'skills/docx' },
      { name: 'pptx', description: 'Extract slide content and speaker notes from PowerPoint', path: 'skills/pptx' },
      { name: 'xlsx', description: 'Process Excel spreadsheets with formula and chart support', path: 'skills/xlsx' },
      { name: 'frontend-design', description: 'Generate frontend designs from descriptions', path: 'skills/frontend-design' },
      { name: 'webapp-testing', description: 'Automated web application testing', path: 'skills/webapp-testing' },
      { name: 'mcp-builder', description: 'Build Model Context Protocol servers', path: 'skills/mcp-builder' },
      { name: 'skill-creator', description: 'Create new Agent Skills from scratch', path: 'skills/skill-creator' },
      { name: 'claude-api', description: 'Work with the Claude API directly', path: 'skills/claude-api' },
      { name: 'canvas-design', description: 'Design visual layouts on canvas', path: 'skills/canvas-design' },
    ],
  },
  {
    id: 'awesome-cursorrules',
    name: 'Awesome CursorRules',
    description: '179 curated .cursorrules for popular frameworks: React, Next.js, Vue, Svelte, FastAPI, Django, and more. The definitive collection of Cursor AI configurations.',
    source: 'github',
    repoUrl: 'https://github.com/PatrickJS/awesome-cursorrules',
    owner: 'PatrickJS',
    stars: 38455,
    forks: 3256,
    lastUpdated: '2025-10-24',
    creator: '@PatrickJS',
    createdAt: '2024-09-01',
    tags: ['cursor', 'rules', 'frameworks', 'coding', 'standards'],
    compatibility: ['cursor', 'windsurf'],
    trustTier: 'community',
    detectedFiles: ['.cursorrules'],
    skills: [
      { name: 'react', description: 'React best practices: hooks, composition, performance', path: 'rules-new/react.mdc' },
      { name: 'nextjs', description: 'Next.js patterns: App Router, server components, caching', path: 'rules-new/nextjs.mdc' },
      { name: 'vue', description: 'Vue 3 conventions: Composition API, Pinia, TypeScript', path: 'rules-new/vue.mdc' },
      { name: 'svelte', description: 'Svelte coding style and SvelteKit patterns', path: 'rules-new/svelte.mdc' },
      { name: 'fastapi', description: 'FastAPI structure: dependency injection, async patterns', path: 'rules-new/fastapi.mdc' },
      { name: 'typescript', description: 'TypeScript strict mode and type safety patterns', path: 'rules-new/typescript.mdc' },
      { name: 'tailwind', description: 'Tailwind CSS utility-first patterns', path: 'rules-new/tailwind.mdc' },
      { name: 'rust', description: 'Rust idioms and safety patterns', path: 'rules-new/rust.mdc' },
    ],
  },
  {
    id: 'garrytan-gstack',
    name: 'gstack',
    description: 'Garry Tan\'s Claude Code stack: CEO review, engineering review, code review, browser QA, shipping, and retro. Battle-tested by YC founders.',
    source: 'github',
    repoUrl: 'https://github.com/garrytan/gstack',
    owner: 'garrytan',
    stars: 10243,
    forks: 1222,
    lastUpdated: '2026-03-14',
    creator: '@garrytan',
    createdAt: '2026-01-15',
    tags: ['planning', 'review', 'shipping', 'automation', 'startup'],
    compatibility: ['claude-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'CLAUDE.md'],
    skills: [
      { name: 'plan-ceo-review', description: 'CEO-level planning and prioritization before building features', path: 'plan-ceo-review' },
      { name: 'plan-eng-review', description: 'Engineering review of implementation approach and edge cases', path: 'plan-eng-review' },
      { name: 'review', description: 'Code review with startup velocity focus — practical feedback, not nitpicks', path: 'review' },
      { name: 'ship', description: 'Deploy and announce features with confidence', path: 'ship' },
      { name: 'browse', description: 'Browser automation for testing user flows and competitor research', path: 'browse' },
      { name: 'qa', description: 'Systematic QA checklist for critical paths', path: 'qa' },
      { name: 'setup-browser-cookies', description: 'Authenticate browser sessions for realistic testing', path: 'setup-browser-cookies' },
      { name: 'retro', description: 'Post-ship retrospective: what worked, what didn\'t, what\'s next', path: 'retro' },
    ],
  },
  {
    id: 'github-awesome-copilot',
    name: 'Awesome Copilot',
    description: 'GitHub\'s official community collection: 100+ skills, hooks, agents, and configurations for GitHub Copilot. Instructions, workflows, and plugins.',
    source: 'github',
    repoUrl: 'https://github.com/github/awesome-copilot',
    owner: 'github',
    stars: 25167,
    forks: 2881,
    lastUpdated: '2026-03-13',
    creator: '@github',
    createdAt: '2025-06-11',
    tags: ['copilot', 'github', 'official', 'agents', 'workflows'],
    compatibility: ['github-copilot', 'vs-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'AGENTS.md'],
    skills: [
      { name: 'azure-deploy', description: 'Deploy applications to Azure services', path: 'skills/azure-deployment-preflight' },
      { name: 'azure-cost-optimize', description: 'Analyze and optimize Azure cloud spending', path: 'skills/az-cost-optimize' },
      { name: 'architecture-blueprint', description: 'Generate architecture diagrams and blueprints', path: 'skills/architecture-blueprint-generator' },
      { name: 'appinsights-instrumentation', description: 'Add Application Insights telemetry to projects', path: 'skills/appinsights-instrumentation' },
      { name: 'bigquery-pipeline-audit', description: 'Audit BigQuery data pipelines', path: 'skills/bigquery-pipeline-audit' },
      { name: 'agentic-eval', description: 'Evaluate and test AI agent configurations', path: 'skills/agentic-eval' },
    ],
  },
  {
    id: 'vercel-agent-skills',
    name: 'Vercel Agent Skills',
    description: 'Vercel\'s official agent skills: React best practices, web design guidelines, composition patterns, and deploy-to-Vercel automation.',
    source: 'github',
    repoUrl: 'https://github.com/vercel-labs/agent-skills',
    owner: 'vercel-labs',
    stars: 22994,
    forks: 2066,
    lastUpdated: '2026-03-12',
    creator: '@vercel',
    createdAt: '2025-12-08',
    tags: ['vercel', 'react', 'design', 'deploy', 'official'],
    compatibility: ['claude-code', 'cursor', 'github-copilot', 'vs-code', 'gemini-cli'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md', 'AGENTS.md', 'CLAUDE.md'],
    skills: [
      { name: 'react-best-practices', description: 'React patterns, hooks, and component architecture', path: 'skills/react-best-practices' },
      { name: 'web-design-guidelines', description: 'Web design principles and UI/UX guidelines', path: 'skills/web-design-guidelines' },
      { name: 'composition-patterns', description: 'Component composition and reuse patterns', path: 'skills/composition-patterns' },
      { name: 'deploy-to-vercel', description: 'Deploy projects to Vercel platform', path: 'skills/deploy-to-vercel' },
      { name: 'react-native-skills', description: 'React Native development patterns', path: 'skills/react-native-skills' },
    ],
  },
  {
    id: 'microsoft-copilot-azure',
    name: 'GitHub Copilot for Azure',
    description: 'Microsoft\'s official Azure Copilot skills: cloud deployment, cost optimization, diagnostics, compliance, AI gateway, and 20+ more.',
    source: 'github',
    repoUrl: 'https://github.com/microsoft/GitHub-Copilot-for-Azure',
    owner: 'microsoft',
    stars: 154,
    forks: 100,
    lastUpdated: '2026-03-14',
    creator: '@microsoft',
    createdAt: '2024-10-01',
    tags: ['azure', 'cloud', 'devops', 'infrastructure', 'official'],
    compatibility: ['github-copilot', 'vs-code'],
    trustTier: 'verified',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'azure-deploy', description: 'Deploy applications to Azure compute services', path: 'plugin/skills/azure-deploy' },
      { name: 'azure-cost-optimization', description: 'Analyze and optimize cloud spending', path: 'plugin/skills/azure-cost-optimization' },
      { name: 'azure-diagnostics', description: 'Diagnose and troubleshoot Azure resources', path: 'plugin/skills/azure-diagnostics' },
      { name: 'azure-compliance', description: 'Check compliance and security posture', path: 'plugin/skills/azure-compliance' },
      { name: 'azure-ai', description: 'Azure AI services integration', path: 'plugin/skills/azure-ai' },
      { name: 'azure-aigateway', description: 'Azure AI Gateway configuration', path: 'plugin/skills/azure-aigateway' },
      { name: 'azure-resource-visualizer', description: 'Visualize Azure resource relationships', path: 'plugin/skills/azure-resource-visualizer' },
    ],
  },
  {
    id: 'planning-with-files',
    name: 'Planning with Files',
    description: 'Manus-style persistent markdown planning for Claude Code. The workflow pattern behind the $2B acquisition — structured thinking with file-based plans.',
    source: 'github',
    repoUrl: 'https://github.com/OthmanAdi/planning-with-files',
    owner: 'OthmanAdi',
    stars: 16061,
    forks: 1476,
    lastUpdated: '2026-03-14',
    creator: '@OthmanAdi',
    createdAt: '2026-01-03',
    tags: ['planning', 'workflow', 'methodology', 'claude-code'],
    compatibility: ['claude-code'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'planning-with-files', description: 'Persistent markdown planning: create, update, and track plans as files' },
    ],
  },
  {
    id: 'claude-scientific-skills',
    name: 'Claude Scientific Skills',
    description: '200+ skills for research, science, engineering, and finance. Covers bioinformatics, chemistry, data analysis, quantum computing, and scientific writing.',
    source: 'github',
    repoUrl: 'https://github.com/K-Dense-AI/claude-scientific-skills',
    owner: 'K-Dense-AI',
    stars: 14872,
    forks: 1635,
    lastUpdated: '2026-03-11',
    creator: '@K-Dense-AI',
    createdAt: '2025-10-19',
    tags: ['science', 'research', 'bioinformatics', 'data-analysis', 'academic'],
    compatibility: ['claude-code', 'claude'],
    trustTier: 'community',
    detectedFiles: ['SKILL.md'],
    skills: [
      { name: 'arxiv-database', description: 'Search and retrieve papers from arXiv', path: 'scientific-skills/arxiv-database' },
      { name: 'literature-review', description: 'Systematic literature review and synthesis', path: 'scientific-skills/literature-review' },
      { name: 'scientific-writing', description: 'Academic paper writing with proper structure', path: 'scientific-skills/scientific-writing' },
      { name: 'exploratory-data-analysis', description: 'EDA with statistical summaries and visualizations', path: 'scientific-skills/exploratory-data-analysis' },
      { name: 'rdkit', description: 'Molecular chemistry with RDKit', path: 'scientific-skills/rdkit' },
      { name: 'alphafold-database', description: 'Protein structure prediction via AlphaFold', path: 'scientific-skills/alphafold-database' },
      { name: 'qiskit', description: 'Quantum computing with Qiskit', path: 'scientific-skills/qiskit' },
      { name: 'statistical-analysis', description: 'Statistical testing and inference', path: 'scientific-skills/statistical-analysis' },
    ],
  },

]
